// app/components/FeaturesSection.tsx
'use client'

import { FaBullseye, FaBolt, FaChartLine, FaRobot } from 'react-icons/fa'

const features = [
  {
    icon: <FaBullseye className="text-xl text-gray-100" />,
    title: 'Personalized Skill Plans',
    description: 'Get learning plans tailored to your goals and time. No fluff, just focus.',
  },
  {
    icon: <FaBolt className="text-xl text-gray-100" />,
    title: 'AI-powered Suggestions',
    description: 'Let AI guide your learning with smart topic recommendations.',
  },
  {
    icon: <FaChartLine className="text-xl text-gray-100" />,
    title: 'Track Progress Visually',
    description: 'View your streak, progress %, and completed tasks in a clean dashboard.',
  },
    {
    icon: <FaRobot className='text-xl text-gray-180' />,
    title: "AI-Curated Learning",
    description: "Receive fresh, personalized topics daily — generated by AI to match your learning goals and pace."
    }
]

const FeaturesSection = () => {
  return (
    <section className="bg-black border-t border-gray-800 py-16">
      <div className="max-w-6xl mx-auto px-6">
        <h2 className="text-3xl sm:text-4xl font-bold text-white mb-10 text-center">
          Why SkillSprint?
        </h2>
        <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-2">
          {features.map((feature, index) => (
            <div key={index} className="bg-gray-900 p-6 rounded-2xl shadow hover:shadow-lg transition-shadow">
              <div className="flex items-center justify-center w-12 h-12 rounded-lg bg-gray-800 mb-4">
                {feature.icon}
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">{feature.title}</h3>
              <p className="text-sm text-gray-400">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}

export default FeaturesSection
