import { geminiClient } from "./geminiClient.js";

import { ApiError } from "./apiError.js";
import { titleToHtmlFriendly } from "simple-icons/sdk";


const generateSkillLevel = async ({skillName, category}) => {
        try {
            const prompt = `
                You are an AI classifier.
            
                Your task is to assign a skill level to the following skill based on its name and category.
            
                The possible levels are:
                - beginner
                - intermediate
                - advanced
                - expert
            
                Skill Name: ${skillName}
                Category: ${category}
            
                Respond with only **one** word: the most appropriate level **exactly as listed above**.
                Do NOT explain. Do NOT include extra text.
            
                Just return one of: beginner, intermediate, advanced, expert.
                `.trim();
        
            const level = await geminiClient(prompt);
        
            const normalized = level.trim().toLowerCase();
        
            const validLevels = ["beginner", "intermediate", "advanced", "expert"];
        
            if (!validLevels.includes(normalized)) {
                throw new ApiError(500, "Invalid level generated by AI");
            }
        
            return normalized;
        } catch (error) {
            console.log("AI skill level generation failed ", error)
            throw new ApiError(500, "Failed to generate skill level")     
    }
};


export default generateSkillLevel;